# Generated by Django 2.2.7 on 2019-11-22 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=280)),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_stats', models.CharField(choices=[('N', 'New'), ('IP', 'IN Progress'), ('D', 'Done'), ('I', 'Invalid')], default='N', max_length=180)),
                ('assigneduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloodsign', to=settings.AUTH_USER_MODEL)),
                ('completeuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finisher', to=settings.AUTH_USER_MODEL)),
                ('user_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
